version: '3.8'

services:
  plexlocalscan:
    build: .
    environment:
      - PLEX_HOST=plex
      - PLEX_PORT=32400
      - PLEX_TOKEN=your_plex_token_here
    volumes:
      - /path/to/your/movies:/media/movies:ro
      - /path/to/your/shows:/media/shows:ro
    networks:
      - plex_network

networks:
  plex_network:
    external: true 