services:
  plexlocalscan-api:
    build: .
    container_name: plexlocalscan-api
    ports:
      - "3000:3000"
    volumes:
      - D:\Test2:/mnt/zurg/tvseries
      - D:\TestSymlink:/mnt/organized/tvseries
      - D:\config:/app/config
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - NODE_ENV=production
    restart: unless-stopped
