services:
  mediaflick-plexlocalscan-api:
    build: .
    user: pho
    container_name: mediaflick-plexlocalscan-api
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - /mnt/zurg/tvseries:/mnt/zurg/tvseries
      - /mnt/zurg/movies:/mnt/zurg/movies
      - /mnt/organized/tvseries:/mnt/organized/tvseries
      - /mnt/organized/movies:/mnt/organized/movies
      - /opt/mediaflick:/app/config
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - NODE_ENV=production
    restart: unless-stopped
