version: '3.8'

services:
  plexlocalscan:
    build: .
    container_name: plexlocalscan
    volumes:
      - ./config:/config
      - /downloads:/downloads
      - /media:/media
    restart: unless-stopped

networks:
  plex_network:
    external: true